Document: snapfly
Title: Debian snapfly Manual
Author: <insert document author here>
Abstract: This manual describes what snapfly is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/snapfly/snapfly.sgml.gz

Format: postscript
Files: /usr/share/doc/snapfly/snapfly.ps.gz

Format: text
Files: /usr/share/doc/snapfly/snapfly.text.gz

Format: HTML
Index: /usr/share/doc/snapfly/html/index.html
Files: /usr/share/doc/snapfly/html/*.html
